### ISSUE TITLE
Make proper Dataset class and create preliminary function

### ISSUE THREAD

**Issue by dbisk** [soosiey/bengali-character-recognition#1]
Create a preliminary function to load all the parquet files into the program and the separate them into training and testing sets, with randomization probably.

**Comment by soosiey** [comment]
Got a proper dataset class, but shuffling throws memory errors

**Comment by dbisk** [comment]
I can work on the shuffling specifics today (5/12)

**Comment by dbisk** [comment]
Completed but uses a *ton* (~15gb peak) of a memory in order to perform adequate shuffling.
